### ISSUE TITLE
Change font-size for meter_rg 

### ISSUE THREAD

**Issue by flighter18** [Jackuna/Nagraj#2] opened 2018-11-08 20:46 UTC
Hi 

First of all. it is a super dashing. Thank you soo mutch!

I would like to change the font size inside the graphics.i have tried many different ways but with no luck. Strangely, the text inside some graphics are bigger than in others. 

Is it possible to standardize the text size inside the graphics?

Thank you
Best regards
Raphael

**Comment by Jackuna** [comment] 2018-11-11 08:05
Thanks Raphael for appreciating my efforts 👍 
Do let me know the tiles no, where you see inconsistency for the font size within the meter graphics.
Attached a screenshot for reference, that i freshly installed.

If you are asking for the meter_rg ( Red-Green),  the one that uses meter_rg widgets are highlighted,
rest all are using simple meter widget. 
Yes, apart from meter and meter_rg widget all have different custom fonts that you can change.
![image](https://user-images.githubusercontent.com/20737721/48310453-53a58d80-e5b5-11e8-83bd-d351a2644c7e.png)

**Comment by flighter18** [comment] 2018-11-11 11:51
Hi Jackuna thank you for the message.
As you can see on my printscreen (black circle) the "host Down" meter_rg has a different font site as the "service critical" meter_rg.
Furthermore the service warning has also a different font size.

my goal is that all this widgets has the same font size.
I have tried many things but i couldn't get it work.

________________________________
Von: JacKuna <notifications@github.com>
Gesendet: Sonntag, 11. November 2018 09:05
An: Jackuna/nagraj
Cc: flighter18; Author
Betreff: Re: [Jackuna/nagraj] Change font-size for meter_rg (#2)


Thanks Raphael for appreciating my efforts 👍
Do let me know the tiles no, where you see inconsistency for the font size within the meter graphics.
Attached a screenshot for reference, that i freshly installed.

If you are asking for the meter_rg ( Red-Green), the one that uses meter_rg widgets are highlighted,
rest all are using simple meter widget.
Yes, apart from meter and meter_rg widget all have different custom fonts that you can change.
[image]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20737721%2F48310453-53a58d80-e5b5-11e8-83bd-d351a2644c7e.png&data=02%7C01%7C%7Cb29eec7dd9234411ec8b08d647ac65bd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636775203091252891&sdata=iCuBvYenPYvHkklCiZqHRuMhpt%2FYUjZPV9zW6zOfOm8%3D&reserved=0>

**Comment by Jackuna** [comment] 2018-11-11 13:06
attach your screenshot, it's missing. :)

**Comment by flighter18** [comment] 2018-11-11 19:44
Sh**t 😊
Here you go.
________________________________
Von: JacKuna <notifications@github.com>
Gesendet: Sonntag, 11. November 2018 14:06
An: Jackuna/nagraj
Cc: flighter18; Author
Betreff: Re: [Jackuna/nagraj] Change font-size for meter_rg (#2)


attach your screenshot, it's missing. :)

**Comment by Jackuna** [comment] 2018-11-11 19:50
It's still missing dear.
BTW font size is same for all the meter grid, it's the color contrast that makes you feel it.

**Comment by flighter18** [comment] 2018-11-12 19:53
That is really strange i attached the picture both time 😊 maybe github doesen't allow to send pictures.
I uploaded the picture to weshare.com and this is the link:

<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwe.tl%2Ft-iSgQ65adTw&data=02%7C01%7C%7C762f04e7fbd64787403308d648d78c27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636776487930624612&sdata=Tdk2ejt9xywXddIIZCHQvrSRozBmqMvD4FRWeF4KcTA%3D&reserved=0>
https://wetransfer.com/downloads/c61b0454e5e9e3de937ec40b0c49c0f720181112194619/9e5f60

I have compared the font size with the developer mode of firefox and the font size hasen't the same size.
But i think the reason for that is, i have changed some code for example:
The pictures size. (data-height and data-width)


Von: JacKuna <notifications@github.com>
Gesendet: Sonntag, 11. November 2018 20:50
An: Jackuna/nagraj
Cc: flighter18; Author
Betreff: Re: [Jackuna/nagraj] Change font-size for meter_rg (#2)


It's still missing dear.
BTW font size is same for all the meter grid, it's the color contrast that makes you feel it.

**Comment by Jackuna** [comment] 2018-11-15 00:44
Yes, may be this might be effecting it, and you can adjust within the css file of corresponding widget.

**Comment by Jackuna** [comment] 2018-11-15 01:20
![image](https://user-images.githubusercontent.com/20737721/48523425-6b755e00-e8a2-11e8-8733-dcdac7fe44e8.png)

Here is some artifact for developer tools, it's same for me.
In case if you feel it's not uniform you can change the same within widget's css file font parameter.

**Comment by Jackuna** [comment] 2018-11-15 01:21
I may say it's not a bug, closing the issue :)

**Closed as completed** 2018-11-15 01:22 UTC
Labels: help wanted, good first issue

**Comment by flighter18** [comment] 2018-11-18 22:20
it is truly not a bug 😄
Sorry to bother you.

________________________________
Von: JacKuna <notifications@github.com>
Gesendet: Donnerstag, 15. November 2018 02:21
An: Jackuna/nagraj
Cc: flighter18; Author
Betreff: Re: [Jackuna/nagraj] Change font-size for meter_rg (#2)


I may say it's not a bug, closing the issue :)

**Comment by flighter18** [comment] 2018-11-18 22:22
Thank you for the hint. i will try it out this week 😄
________________________________
Von: JacKuna <notifications@github.com>
Gesendet: Donnerstag, 15. November 2018 02:20
An: Jackuna/nagraj
Cc: flighter18; Author
Betreff: Re: [Jackuna/nagraj] Change font-size for meter_rg (#2)


[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20737721%2F48523425-6b755e00-e8a2-11e8-8733-dcdac7fe44e8.png&data=02%7C01%7C%7C2bf95c0a46d84b04ff8b08d64a9884e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636778416248263945&sdata=IwtqRVPDDD4tIP56unkUjR%2Bn5V88YRo%2B2F8ofX3ciCM%3D&reserved=0>

Here is some artifact for developer tools, it's same for me.
In case if you feel it's not uniform you can change the same within widget's css file font parameter.
